#File di configurazione per il GEC Tracker

[GENERALE]
#Sezione per parametri generali

#Tipo di tracker utilizzato (WIP)
#Possibili opzioni:
#- Scroll: crea la finestra con barre a scorrimento e adattabile in larghezza
#- Stream: crea una finstra a dimensioni fisse
Window_type = Stream

#Generazione giocata (WIP)
#Possibili opzioni:
#- OA: Oro/Argento
Gen = OA


[INTEGRAZIONE TWITCH]
#Gestione dell'interazione del tool con la chat di twitch

#Attiva l'interazione tra strumento e chat twitch. Mettere a True per attivare. Default: False
# Se messa a False, i comandi successivi possono essere lasciati vuoti
USE_TWITCH = False

#username del canale a cui collegarsi
channel= yammar_option

#Lista degli utenti (in minuscolo) autorizzati a controllare il tracker
mods= mod1, mod2, mod3,yammar_option

#Velocità di processing dei messaggi in secondi. 
#Più è alta più velocemente processiamo messaggi con il rischio di finirli e dover aspettare.
#Più è bassa più aumenta il delay tra comando e azione, ma con meno sprechi se non ci sono messaggi.
message_rate= 0.5

#Numero massimo di messaggi da processare per loop
queue_length= 10

#Numero massimo di thread impiegati per processare i mes￾saggi
workers= 1

#Quanti messaggi totali chat leggere dalla prima di forzare un salvataggio dei dati. Mettere a 0 per disabilitare l’opzione
BACKUP_COUNTER=10

#Comando per marcare un pokemon:
CMD_ADD_POKEMON=!MARKMON
#Comando per smarcare un pokemon:
CMD_ADD_POKEMON_BLUE=!MARKBLU
#Comando per marcare in blu un pokemon:
CMD_REMOVE_POKEMON=!UNMARKMON
#Comando per marcare un allenatore:
CMD_ADD_TRAINER=!MARKTRAINER
CMD_REMOVE_TRAINER=!UNMARKTRAINER
#Comando per marcare un oggetto:
CMD_ADD_ITEM=!MARKITEM
#Comando per smarcare un oggetto:
CMD_REMOVE_ITEM=!UNMARKITEM
#Comando per marcare un evento
CMD_ADD_MISC=!MARKMISC
#Comando per smarcare un evento
CMD_REMOVE_MISC=!UNMARKMISC
#Comando per marcare una mossa
CMD_ADD_MOVE=!MARKMOVE
#Comando per smarcare una mossa
CMD_REMOVE_MOVE=!UNMARKMOVE

[MONITOR GIOCO]
#Gestione dell'interazione del tool con la lo script che legge i dati dalla memoria di gioco 

#Attiva l'opzione per leggere i dati dalla memoria di gioco. Da usare insieme allo script per leggere
# effettivamente i dati. Default: False
USE_MONITOR = False

#Porta su cui avviare la comunicazione. Default: 9999
port = 9999

#Secondi da aspettare prima di considerare la comunicazione terminata e rimettersi in attesa
timeout=30