#Configuration file for the GET
[GENERAL]
#Section for general parameters

#Type of tracker used
#Possible options:
#- Scroll: creates a window with scroll bars and adjustable width
#- Stream: creates a window with fixed dimensions
Window_type = Stream

#Game generation
#Possible options:
#- RBY: Red/Blue/Yellow
#- GS: Gold/Silver
Gen = GS


[TWITCH INTEGRATION]
#Manages the interaction of the tool with Twitch chat

#Enables interaction between the tool and Twitch chat. Set to True to enable. Default: False
# If set to False, the subsequent commands can be left empty
USE_TWITCH = False

#Username of the channel to connect to
channel= channel

#List of users (in lowercase) authorized to control the tracker
mods= mod1, mod2, mod3

#Message processing speed in seconds. 
#Higher values process messages faster but risk depleting the queue, requiring waiting.
#Lower values increase the delay between command and action but minimize waste if there are few messages.
message_rate= 0.5

#Maximum number of messages to process per loop
queue_length= 10

#Maximum number of threads used to process messages
workers= 1

#Total number of chat messages to read before forcing a data save. Set to 0 to disable this option.
BACKUP_COUNTER=10

#Command to mark a Pokémon:
CMD_ADD_POKEMON=!MARKMON
#Command to unmark a Pokémon:
CMD_REMOVE_POKEMON=!UNMARKMON
#Command to mark a Pokémon in blue:
CMD_ADD_POKEMON_BLUE=!MARKBLU
#Command to mark a trainer:
CMD_ADD_TRAINER=!MARKTRAINER
#Command to unmark a trainer:
CMD_REMOVE_TRAINER=!UNMARKTRAINER
#Command to mark an item:
CMD_ADD_ITEM=!MARKITEM
#Command to unmark an item:
CMD_REMOVE_ITEM=!UNMARKITEM
#Command to mark an event
CMD_ADD_MISC=!MARKMISC
#Command to unmark an event
CMD_REMOVE_MISC=!UNMARKMISC
#Command to mark a move
CMD_ADD_MOVE=!MARKMOVE
#Command to unmark a move
CMD_REMOVE_MOVE=!UNMARKMOVE

[GAME MONITOR]
#Manages the interaction of the tool with the script that reads data from the game's memory 

#Enables the option to read data from the game's memory. To be used with the script to actually read the data. Default: False
USE_MONITOR = False

#Port to start the communication. Default: 9999
port = 9999

#Seconds to wait before considering the communication terminated and resuming standby
timeout=30
